"""Backtesting data models for local research evidence."""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum

from pydantic import BaseModel, Field, model_validator


class BacktestMode(StrEnum):
    """Supported Phase 4 backtest modes."""

    SIMPLE_CLOSE_ABOVE_PRIOR_CLOSE = "simple_close_above_prior_close"


class OrderSide(StrEnum):
    """Simulated side for a local research fill."""

    BUY = "buy"
    SELL = "sell"


class SimulatedOrderType(StrEnum):
    """Simulated order type."""

    MARKET = "market"


class BacktestStatus(StrEnum):
    """Backtest lifecycle status."""

    COMPLETED = "completed"
    UNSUPPORTED_STRATEGY = "unsupported_strategy"
    QUALITY_FAILED = "quality_failed"
    NO_DATA = "no_data"


class ExecutionAssumptions(BaseModel):
    """Deterministic execution assumptions for local fixture backtests."""

    initial_capital: float = Field(default=50_000.0, gt=0)
    commission_per_trade: float = Field(default=0.0, ge=0)
    slippage_bps: float = Field(default=0.0, ge=0)
    max_position_pct: float = Field(default=0.25, gt=0, le=1.0)
    allow_fractional_shares: bool = True
    execution_timing: str = Field(default="next_open", pattern="^(next_open|next_close)$")
    benchmark_symbol: str = "SPY"

    @model_validator(mode="after")
    def normalize_benchmark(self) -> ExecutionAssumptions:
        """Normalize benchmark symbols."""

        self.benchmark_symbol = self.benchmark_symbol.strip().upper()
        if not self.benchmark_symbol:
            raise ValueError("benchmark_symbol must be non-empty")
        return self


class BacktestRequest(BaseModel):
    """Request for a local fixture backtest."""

    strategy_id: str = Field(min_length=1)
    symbol: str = Field(min_length=1)
    start_timestamp: datetime | None = None
    end_timestamp: datetime | None = None
    initial_capital: float = Field(default=50_000.0, gt=0)
    execution_assumptions: ExecutionAssumptions = Field(default_factory=ExecutionAssumptions)

    @model_validator(mode="after")
    def validate_window_and_symbols(self) -> BacktestRequest:
        """Normalize text and validate optional time window."""

        self.strategy_id = self.strategy_id.strip()
        self.symbol = self.symbol.strip().upper()
        if not self.strategy_id:
            raise ValueError("strategy_id must be non-empty")
        if not self.symbol:
            raise ValueError("symbol must be non-empty")
        if (
            self.start_timestamp is not None
            and self.end_timestamp is not None
            and self.start_timestamp > self.end_timestamp
        ):
            raise ValueError("start_timestamp must be before end_timestamp")
        return self


class SimulatedFill(BaseModel):
    """Auditable simulated fill generated by the research engine."""

    timestamp: datetime
    side: OrderSide
    order_type: SimulatedOrderType = SimulatedOrderType.MARKET
    quantity: float
    price: float
    commission: float
    slippage_bps: float


class SimulatedTrade(BaseModel):
    """Closed simulated research position."""

    strategy_id: str
    symbol: str
    entry_fill: SimulatedFill
    exit_fill: SimulatedFill
    quantity: float
    gross_pnl: float
    net_pnl: float
    return_pct: float
    holding_period_bars: int
    exit_reason: str


class EquityCurvePoint(BaseModel):
    """Point-in-time portfolio equity record."""

    timestamp: datetime
    cash: float
    position_quantity: float
    position_market_value: float
    equity: float


class BacktestQualityIssue(BaseModel):
    """Structured backtest issue."""

    code: str = Field(min_length=1)
    message: str = Field(min_length=1)
    severity: str = "warning"


class BacktestResult(BaseModel):
    """Research-only backtest result."""

    strategy_id: str
    symbol: str
    status: BacktestStatus
    initial_capital: float
    final_equity: float
    total_return_pct: float
    max_drawdown_pct: float
    trade_count: int
    winning_trade_count: int
    losing_trade_count: int
    win_rate_pct: float
    average_win_pct: float | None
    average_loss_pct: float | None
    profit_factor: float | None
    exposure_pct: float
    trades: list[SimulatedTrade] = Field(default_factory=list)
    equity_curve: list[EquityCurvePoint] = Field(default_factory=list)
    quality_issues: list[BacktestQualityIssue] = Field(default_factory=list)
    assumptions_summary: dict[str, object] = Field(default_factory=dict)
    conclusion: str = "research_only"
